# Generated by Django 3.2 on 2021-04-26 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_rating_takeagain'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rating.university'),
        ),
    ]
