# Generated by Django 3.2 on 2021-04-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_auto_20210426_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='attendance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='credit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='grade',
            field=models.CharField(choices=[('A', 'A'), ('BP', 'BP'), ('B', 'B'), ('CP', 'CP'), ('C', 'C'), ('DP', 'DP'), ('D', 'D'), ('F', 'F')], default='A', max_length=2),
        ),
        migrations.AddField(
            model_name='rating',
            name='textbook',
            field=models.BooleanField(default=True),
        ),
    ]
